// Hand-rolled mirror of the config struct that `cargo anypoint config`
// (a.k.a. `make build-asset-files`) generates from definition/gcl.yaml.
//
// In a typical PDK project this file lives at src/generated/config.rs
// and is regenerated by the build. Until the project is initialized
// via `anypoint-cli-v4 pdk policy-project create`, we keep a hand-
// rolled copy here so the rest of the Rust code compiles. After the
// real generated module exists, delete this file and `mod config;` in
// lib.rs in favour of `mod generated; use crate::generated::config::Config;`.
//
// Field names are camelCase in YAML and snake_case here; serde maps via
// `rename_all = "camelCase"`.

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Config {
    /// Cerberus event_ingest upstream — Envoy cluster reference.
    pub ingest_service: String,

    /// Cerberus API key. Sent as the X-API-Key header on outbound
    /// requests; the server resolves client_id from the key.
    pub token: String,

    /// Optional. HMAC-SHA256 key for PII hashing.
    pub secret_key: Option<String>,

    /// Optional. Base URL to fetch the HMAC key from at startup.
    pub backend_url: Option<String>,

    /// Header to read client IP from. Default: X-Forwarded-For.
    #[serde(default = "default_client_ip_header")]
    pub client_ip_header: String,

    /// Optional. Header to read end-user identity from.
    pub user_id_header: Option<String>,

    /// Optional glob allowlist.
    pub capture_paths: Option<Vec<String>>,

    /// Optional glob denylist.
    pub exclude_paths: Option<Vec<String>>,

    /// Buffer + sanitize JSON request bodies. Default: true.
    #[serde(default = "default_capture_request_body")]
    pub capture_request_body: bool,

    /// Max events per outbound batch. Default: 50.
    #[serde(default = "default_batch_size")]
    pub batch_size: u32,

    /// Flush interval in milliseconds. Default: 2000.
    #[serde(default = "default_flush_interval_ms")]
    pub flush_interval_ms: u32,

    /// Per-worker queue capacity. Default: 10000.
    #[serde(default = "default_queue_capacity")]
    pub queue_capacity: u32,

    /// Log verbosity. Default: info.
    /// TODO(v1.1): wire this through to PDK's logger. As of PDK 1.8.0
    /// there is no public API to set per-policy log verbosity at
    /// runtime — the gateway pod's global LOG_LEVEL env var dominates.
    /// We accept the field anyway so config remains forward-compatible
    /// (and matches Django's CERBERUS_DEBUG knob in the docs).
    #[serde(default = "default_log_level")]
    #[allow(dead_code)]
    pub log_level: String,
}

fn default_client_ip_header() -> String {
    "X-Forwarded-For".to_string()
}
fn default_capture_request_body() -> bool {
    true
}
fn default_batch_size() -> u32 {
    50
}
fn default_flush_interval_ms() -> u32 {
    2000
}
fn default_queue_capacity() -> u32 {
    10_000
}
fn default_log_level() -> String {
    "info".to_string()
}
